import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from backend.database.models import Patient

def generate_patient_summary_pdf(patient: Patient, visits: list, metrics: list) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    subtitle_style = styles['Heading2']
    normal_style = styles['Normal']
    
    elements = []
    
    # Title
    elements.append(Paragraph(f"Patient Health Summary", title_style))
    elements.append(Spacer(1, 12))
    
    # Calculate age
    if patient.date_of_birth:
        try:
            from datetime import date
            dob = patient.date_of_birth
            if hasattr(dob, "date"):
                dob = dob.date()
            today = date.today()
            age_val = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
            age_str = str(age_val)
        except Exception:
            age_str = "N/A"
    else:
        age_str = "N/A"
    
    # Patient Info
    full_name = f"{patient.first_name or ''} {patient.last_name or ''}".strip() or "N/A"
    elements.append(Paragraph(f"<b>Name:</b> {full_name}", normal_style))
    elements.append(Paragraph(f"<b>Age:</b> {age_str}", normal_style))
    elements.append(Paragraph(f"<b>Gender:</b> {patient.gender or 'N/A'}", normal_style))
    elements.append(Paragraph(f"<b>Contact:</b> {patient.phone or 'N/A'}", normal_style))
    elements.append(Spacer(1, 12))
    
    # Recent Visits
    elements.append(Paragraph("Recent Clinical Visits", subtitle_style))
    if visits:
        visit_data = [["Date", "Complaint/Reason", "Diagnosis"]]
        for v in visits[:5]:
            # visit_date is ISO format string or datetime object
            visit_date_val = v.get("visit_date")
            if visit_date_val:
                if isinstance(visit_date_val, str):
                    date_str = visit_date_val[:10]
                else:
                    date_str = visit_date_val.strftime("%Y-%m-%d")
            else:
                date_str = "N/A"
            visit_data.append([date_str, v.get("chief_complaint") or "N/A", v.get("diagnosis") or "N/A"])
        
        t = Table(visit_data, colWidths=[100, 200, 150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        elements.append(t)
    else:
        elements.append(Paragraph("No recent visits recorded.", normal_style))
    elements.append(Spacer(1, 12))
    
    # Recent Metrics
    elements.append(Paragraph("Recent Health Metrics", subtitle_style))
    if metrics:
        metric_data = [["Date", "Metric", "Value", "Unit"]]
        for m in metrics[:5]:
            date_str = m.get("recorded_at") or "N/A"
            metric_data.append([date_str, m.get("metric_type") or "N/A", str(m.get("value") or "N/A"), m.get("unit") or ""])
            
        t2 = Table(metric_data, colWidths=[120, 120, 100, 100])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        elements.append(t2)
    else:
        elements.append(Paragraph("No recent health metrics recorded.", normal_style))
        
    elements.append(Spacer(1, 24))
    elements.append(Paragraph(f"Generated by AfriHealth Assistant on {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Italic']))
    
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
